apiVersion: v1
kind: Service
metadata:
  name: cms-backend-svc
  namespace: home-cms
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: cms
    component: backend
